name: Lint

on:
  pull_request: {}

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Run linters
        run: make lint-go git-diff

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          skip-pkg-cache: true
          args: --timeout 5m --out-${NO_FUTURE}format colored-line-number
